spring:
  config:
    import:
      - classpath:/application-jwt.yml
      - classpath:/application-file.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/.h2/RecoWRITE
    #    url: jdbc:h2:tcp://localhost/~/RecoWRITE
    username: sa
    password: 1234

  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/RecoWRITE
  #    username: root
  #    password: 1234


  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true


#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect

#server:
#  port: 8081
